version: '3.8'

services:
  postgres:
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=$POSTGRES_USER --dbname=$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  tn_service:
    build: ./services/tn_service
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy


  frontend:
    build: ./services/frontend
    volumes:
      - static_files:/app/production

  nginx:
    build: ./services/nginx
    ports:
      - "80:80"
    volumes:
      - static_files:/usr/share/nginx/html


volumes:
  pgdata:
  static_files: