version: '3.8'

services:
  postgres:
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=$POSTGRES_USER --dbname=$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: postgres

  frontend:
    build: ./services/frontend
    ports:
      - "80:80"

  cms:
    build: ./services/cms
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./services/cms/logs:/app/logs

  tg_bot:
    build: ./services/tg_bot
    depends_on:
      - cms

volumes:
  pgdata: