# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import tn_pb2 as tn__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tn_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class TNStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCallback = channel.unary_unary(
                '/grpc.TN/CreateCallback',
                request_serializer=tn__pb2.RequestCreateCallback.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetCallback = channel.unary_unary(
                '/grpc.TN/GetCallback',
                request_serializer=tn__pb2.RequestGetCallback.SerializeToString,
                response_deserializer=tn__pb2.Callback.FromString,
                _registered_method=True)
        self.GetAllCallbacks = channel.unary_unary(
                '/grpc.TN/GetAllCallbacks',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=tn__pb2.ResponseGetAllCallbacks.FromString,
                _registered_method=True)
        self.GetCallbacksPaginated = channel.unary_unary(
                '/grpc.TN/GetCallbacksPaginated',
                request_serializer=tn__pb2.RequestGetCallbacksPaginated.SerializeToString,
                response_deserializer=tn__pb2.ResponseGetCallbacksPaginated.FromString,
                _registered_method=True)
        self.DeleteCallbackById = channel.unary_unary(
                '/grpc.TN/DeleteCallbackById',
                request_serializer=tn__pb2.RequestDeleteCallbackById.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteCallbackByNumber = channel.unary_unary(
                '/grpc.TN/DeleteCallbackByNumber',
                request_serializer=tn__pb2.RequestDeleteCallbackByNumber.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class TNServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCallback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCallback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllCallbacks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCallbacksPaginated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCallbackById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCallbackByNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TNServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCallback': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCallback,
                    request_deserializer=tn__pb2.RequestCreateCallback.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetCallback': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCallback,
                    request_deserializer=tn__pb2.RequestGetCallback.FromString,
                    response_serializer=tn__pb2.Callback.SerializeToString,
            ),
            'GetAllCallbacks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllCallbacks,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=tn__pb2.ResponseGetAllCallbacks.SerializeToString,
            ),
            'GetCallbacksPaginated': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCallbacksPaginated,
                    request_deserializer=tn__pb2.RequestGetCallbacksPaginated.FromString,
                    response_serializer=tn__pb2.ResponseGetCallbacksPaginated.SerializeToString,
            ),
            'DeleteCallbackById': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCallbackById,
                    request_deserializer=tn__pb2.RequestDeleteCallbackById.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteCallbackByNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCallbackByNumber,
                    request_deserializer=tn__pb2.RequestDeleteCallbackByNumber.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.TN', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc.TN', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TN(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCallback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.TN/CreateCallback',
            tn__pb2.RequestCreateCallback.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCallback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.TN/GetCallback',
            tn__pb2.RequestGetCallback.SerializeToString,
            tn__pb2.Callback.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllCallbacks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.TN/GetAllCallbacks',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            tn__pb2.ResponseGetAllCallbacks.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCallbacksPaginated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.TN/GetCallbacksPaginated',
            tn__pb2.RequestGetCallbacksPaginated.SerializeToString,
            tn__pb2.ResponseGetCallbacksPaginated.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCallbackById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.TN/DeleteCallbackById',
            tn__pb2.RequestDeleteCallbackById.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCallbackByNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.TN/DeleteCallbackByNumber',
            tn__pb2.RequestDeleteCallbackByNumber.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
