version: '3.8'

services:
  postgres:
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "50051:50051"
    depends_on:
      - postgres

volumes:
  pgdata:
  pgadmin-data: