service: Alior-Auth
version: 0.0.1

endpoints:
  grpc-endpoint:
    listen-addr: localhost
    port: 8080
databases:
  auth:
    host: localhost
    port: 5432
    database: auth
    user: auth
    password: aliorAuth
alior-auth:
  default:
    endpoint: grpc-endpoint
    database: auth
    