broker:
  url: amqp://guest:guest@localhost:5672/
  exchange:
    name: ansask
    kind: direct
  publisher:
    name: publisher
    routing_key: ask
  consumer:
    name: consumer
    queue: ans
bot:
  poling_to: 60  