service: Alior-sms
version: 0.0.1

databases:
  smsDatabase:
    engine: postgres
    host: localhost
    port: 5432
    sslmode: disable
    dbName: postgres
    dbUser: postgres
    dbPassword: postgres
    