bot:
  token: '6853105885:AAE0JA44brPTqd5iPQ5f2GN0L-jNQYi8E2A'
  chat_id: 6853105885

grpc_client:
  address: localhost
  port: 50051  # Этот клиент подключается к CMS

grpc_server:
  address: localhost
  port: 50052  # Этот сервер TN
