env: "local"
db:
  postgresql_url: postgres://user:password@postgres:5432/db?sslmode=disable
msgBroker:
  rabbitmq_url: amqp://guest:guest@localhost:5672/
bot:
  token: '6853105885:AAE0JA44brPTqd5iPQ5f2GN0L-jNQYi8E2A'
  chat_id: 6853105885