openapi: 3.0.3

info:
  title: Alior Digital API
  description: API для сайта Alior Digital
  version: 1.0.0

servers:
  - url: https://alior-didgital.com
  
components:
  schemas:
    Callback:
      type: object
      properties:
        idea:
          type: string
          description: Идея
        name:
          type: string
          description: Имя
        phone:
          type: string
          description: Номер телефона
        callbackType:
          type: string
          description: Тип колбэка ("call" | "whatsapp" | "telegram")
          
    generalResponseType:
      type: object
      properties:
        success:
          type: boolean
          description: Успешен ли запрос
        message:
          type: string
          description: Сообщение о статусе запроса

    generalErrorType:
      type: object
      properties:
        error:
          type: string
          description: Текст ошибки
    
paths:
  /v1/service/callback:
    post:
      tags:
        - service
      summary: Запрос на обратный звонок
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Callback'
      responses:
        '200':
          description: Запрос на обратный звонок успешно отправлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generalResponseType'
        '400':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generalErrorType'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generalErrorType'
                
    get:
      tags:
        - service
      summary: Получение списка обратных звонков
      parameters:
        - name: limit
          in: query
          description: Сколько запросов считать
          required: true
          schema:
            type: integer
        - name: offset
          in: query
          description: С какого запроса считать
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Список обратных звонков успешно получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Callback'
        '400':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generalErrorType'        
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generalErrorType'
