openapi: 3.0.3

info:
  title: Alior Digital API
  description: API для сайта Alior Digital
  version: 1.0.0

servers:
  - url: https://alior-didgital.com
  
components:
  schemas:
    Callback:
      type: object
      properties:
        idea:
          type: string
          description: Идея
        name:
          type: string
          description: Имя
        phone:
          type: string
          description: Номер телефона
        type:
          type: string
          description: Тип колбэка ("call" | "whatsapp" | "telegram")
          enum: 
            - "call"
            - "whatsapp"
            - "telegram"
         
    generalErrorType:
      type: object
      properties:
        error:
          type: string
          description: Текст ошибки
    
paths:
  /v1/service/callback:
    post:
      tags:
        - service
      summary: Запрос на обратный звонок
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Callback'
      responses:
        '200':
          description: Запрос на обратный звонок успешно отправлен
        '400':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generalErrorType'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generalErrorType'
                
