name: CI Pipeline for Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-code-alior-cms:
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.SECRET }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'

      - name: Установка reviewdog
        run: go install github.com/reviewdog/reviewdog/cmd/reviewdog@latest
        working-directory:  ./services/alior-cms
      - name: Запуск golangci-lint через Reviewdog
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.2
          echo "Install done"
          golangci-lint run --out-format=line-number --disable typecheck | reviewdog -f=golangci-lint -name="golangci-lint" -reporter=github-pr-review -fail-on-error=true
        working-directory: ./services/alior-cms
      - name: Запуск golint через Reviewdog
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./... | reviewdog -f=golint -name="golint" -reporter=github-pr-review -fail-on-error=true
        working-directory: ./services/alior-cms

  build-alior-cms:
    needs: check-code-alior-cms
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
      - name: Проверка версии Go
        run: go version
      - name: Установка кэша зависимостей
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Установка зависимостей
        run: go mod download
        working-directory: ./services/alior-cms
      - name: Сборка проекта
        run: go build -o /dev/null ./...
        working-directory: ./services/alior-cms

  build-alior-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
      - name: Проверка версии Go
        run: go version
      - name: Установка кэша зависимостей
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Установка зависимостей
        run: go mod tidy
        working-directory: ./services/alior-auth
      - name: Сборка проекта
        run: go build -o /dev/null ./...
        working-directory: ./services/alior-auth

  check-tests-alior-cms:
    defaults:
      run:
        working-directory: ./services/alior-cms
    needs:
      - build-alior-cms
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.4

      - name: Проверка зависимостей
        run: go mod verify

      - name: Сборка
        run: go build -v ./...

      - name: Запуск go vet
        run: go vet ./...

      - name: Запуск тестов
        run: go test -race -vet=off ./...

  check-tests-alior-auth:
    defaults:
      run:
        working-directory: ./services/alior-auth
    needs:
      - build-alior-auth
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.4

      - name: Проверка зависимостей
        run: go mod verify

      - name: Сборка
        run: go build -v ./...

      - name: Запуск go vet
        run: go vet ./...

      - name: Запуск тестов
        run: go test -race -vet=off ./...

  start-qa-test:
    needs:
      - check-tests-alior-auth
      - check-tests-alior-cms
    runs-on: ubuntu-latest
    steps:
      - name: Здесь должны быть твои тесты Кирилл
        run: echo "Добавь запуск своих тестов сюда"
