name: CI Pipeline for Develop Branch

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.4

      - name: Install dependencies
        run: go mod tidy

      - name: Build the project
        run: go build -o start.auth main.go

      - name: Run tests
        run: go test ./...

      - name: Build Docker image
        run: docker build -t alior-auth .

      - name: Run Docker container
        run: docker run --rm alior-auth
