name: CI Pipeline for Develop Branch

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: auth
          POSTGRES_USER: auth
          POSTGRES_PASSWORD: aliorAuth

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: auth
      DB_USER: auth
      DB_PASSWORD: aliorAuth

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.4'

      - name: Display Go version
        run: go version

      - name: Set up dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h ${{ env.DB_HOST }} -p ${{ env.DB_PORT }} -U ${{ env.DB_USER }}; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./services/alior-auth

      - name: Pre-build the project
        run: go build -o /dev/null ./...
        working-directory: ./services/alior-auth

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest
          sudo cp ./bin/golangci-lint /usr/local/bin/

      - name: Run golangci-lint
        run: golangci-lint run ./...
        working-directory: ./services/alior-auth

      - name: Build the project
        run: go build -o start.auth main.go
        working-directory: ./services/alior-auth

      - name: Run tests
        run: go test ./...
        working-directory: ./services/alior-auth

      - name: Build Docker image
        run: docker build -t alior-auth .
        working-directory: ./services/alior-auth

      - name: Run Docker container
        run: docker run --rm --env-file .env alior-auth
        working-directory: ./services/alior-auth
