name: CI Pipeline for Develop Branch

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Display Go version
        run: go version

      - name: Set up dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./services/alior-auth

      - name: Build the project
        run: go build -o start.auth main.go
        working-directory: ./services/alior-auth

      - name: Run tests
        run: go test ./...
        working-directory: ./services/alior-auth

      - name: Build Docker image
        run: docker build -t alior-auth .
        working-directory: ./services/alior-auth

      - name: Run Docker container
        run: docker run --rm alior-auth
