name: CI Pipeline for Main Branch

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  bulid-front-to-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: ./services/frontend

      - name: Build the project
        run: npm run build
        working-directory: ./services/frontend

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  build-alior-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Копирование содержимого на виртуальную машину
        uses: actions/checkout@v4
      - name: Установка golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
      - name: Вывод версии Go
        run: go version
      - name: Установка кэша зависимостей
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Установка зависимостей
        run: go mod tidy
        working-directory: ./services/alior-auth
      - name: Попытка собрать проект
        run: go build -o /dev/null ./...
        working-directory: ./services/alior-auth
  build-alior-api-gw:
     runs-on: ubuntu-latest
     steps:
       - name: Копирование содержимого на виртуальную машину
         uses: actions/checkout@v4
       - name: Установка golang
         uses: actions/setup-go@v5
         with:
           go-version: '1.22.4'
       - name: Вывод версии Go
         run: go version
       - name: Установка кэша зависимостей
         uses: actions/cache@v4
         with:
           path: |
             ~/.cache/go-build
             /go/pkg/mod
           key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
           restore-keys: |
             ${{ runner.os }}-go-
       - name: Установка зависимостей
         run: go mod tidy
         working-directory: ./services/alior-api-gw
       - name: Попытка собрать проект
         run: go build -o /dev/null ./...
         working-directory: ./services/alior-api-gw
  check-tests-alior-auth:
    defaults:
      run:
        working-directory: ./services/alior-auth
    needs:
      - build-alior-auth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.4

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Run tests
        run: go test -race -vet=off ./...

  check-tests-alior-api-gw:
    needs: build-alior-api-gw
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.4

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Run tests
        run: go test -race -vet=off ./...
  deploy-front-to-page:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: bulid-front-to-pages
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist
  start-qa-test:
    needs:
      - check-tests-alior-api-gw
      - check-tests-alior-auth
      - deploy-front-to-page
    runs-on: ubuntu-latest
    steps:
      - name: Здесь должны быть твои тесты Кирилл
        run: echo "Добавь запуск своих тестов сюда


