name: CI Pipeline for Main Branch

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - AS-36

jobs:

  build-alior-sms:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
      - name: Проверка версии Go
        run: go version
      - name: Установка кэша зависимостей
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Установка зависимостей
        run: go mod tidy
        working-directory: ./services/alior-sms
      - name: Сборка проекта
        run: go build -o /dev/null ./...
        working-directory: ./services/alior-sms

  build-alior-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
      - name: Проверка версии Go
        run: go version
      - name: Установка кэша зависимостей
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Установка зависимостей
        run: go mod tidy
        working-directory: ./services/alior-auth
      - name: Сборка проекта
        run: go build -o /dev/null ./...
        working-directory: ./services/alior-auth

  check-tests-alior-sms:
    defaults:
      run:
        working-directory: ./services/alior-sms
    needs:
      - build-alior-sms
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.4

      - name: Проверка зависимостей
        run: go mod verify

      - name: Сборка
        run: go build -v ./...

      - name: Запуск go vet
        run: go vet ./...

      - name: Установка staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Запуск staticcheck
        run: staticcheck ./...

      - name: Установка golint
        run: go install golang.org/x/lint/golint@latest

      - name: Запуск golint
        run: golint ./...

      - name: Запуск тестов
        run: go test -race -vet=off ./...

  check-tests-alior-auth:
    defaults:
      run:
        working-directory: ./services/alior-auth
    needs:
      - build-alior-auth
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.4

      - name: Проверка зависимостей
        run: go mod verify

      - name: Сборка
        run: go build -v ./...

      - name: Запуск go vet
        run: go vet ./...

      - name: Установка staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Запуск staticcheck
        run: staticcheck ./...

      - name: Установка golint
        run: go install golang.org/x/lint/golint@latest

      - name: Запуск golint
        run: golint ./...

      - name: Запуск тестов
        run: go test -race -vet=off ./...

  start-qa-test:
    needs:
      - check-tests-alior-api-gw
      - check-tests-alior-auth
      - check-tests-alior-sms
      - check-tests-alior-cms
      - deploy-front
    runs-on: ubuntu-latest
    steps:
      - name: Здесь должны быть твои тесты Кирилл
        run: echo "Добавь запуск своих тестов сюда"
